# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebe8c79cb79c7ed2fe12366dc3dd5920f898ad068ebda6679fd46dd3c072788c8e5bfef141af0cb26ed8f2a5bbd1b1dc34b762914fe6dd6de07e34e2815c7b6f

test:
  secret_key_base: 5979d293ecb16dded0351c65312bdb7d071f4e64f92e21614bc75fe0330a6924cbb00232a358a15f5eef9e5a83dd1736293eebec9bf4947d05d54171b2509f94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
